version: "3"
services:
  backend-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    container_name: backend-container
    image: backend-image:latest
    ports:
      - "5000:5000"
    networks:
      - my_network
    restart: always

  frontend-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend-container
    image: frontend-image:latest
    ports:
      - "8080:80"
    environment:
      - DISPLAY=:0
      - DOCKER_BACKEND_SERVER_ADDRESS=http://backend-service:5000
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
