version: "3"

services:
  your-qt-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    image: frontend-image
    container_name: frontend-container
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ./your_application_executable
