version: "3"

services:
  your-qt-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    image: frontend-image
    container_name: frontend-container
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./frontend/App-Chess:/app
    command: ["./frontend/App-Chess/build/App-Chess.exe"]
