# Use the official Python image as a base image
FROM python:3.11

WORKDIR /app

COPY backend/. /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "scripts/server.py"]
