FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
    cmake \
    qtbase5-dev \
    build-essential \
    libx11-dev 

ENV DISPLAY=host.docker.internal:0

WORKDIR /app

COPY frontend/. .

RUN make build

CMD ["make", "run"]
